version: '3.8'
services:
  app:
    build: .
    container_name: fab-finder-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm run start:prod
